external:
  api:
    papago:
      url: https://openapi.naver.com
      clientId: UfM8_0BpQj7lFX_CRhxh
      clientSecret: IaP5Y4HwQw

management:
  server:
    port: 8081
  metrics:
    export:
      statsd:
        enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernates:
        format_sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        secific.avro.reader: true
    consumer:
      bootstrap-servers: localhost:9092
      group-id: devwue
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring.json.trusted.packages: com.devwue.spring
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
    listener:
      ack-mode: manual
      concurrency: 1


devwue:
  spring:
    api:
      datasource:
        master:
          driver-class-name: org.mariadb.jdbc.Driver
          jdbc-url: jdbc:mariadb://127.0.0.1:11801/devwue?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
          username: root
          password: root
          pool-name: DBMaster-pool
          minimum-idle: 1
          maximum-pool-size: 5
          register-mbeans: true
          connection-timeout: 3000
          idle-timeout: 10000
          validation-timeout: 60000
          max-lifetime: 61000
          data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
          registerMbeans: true
        slave:
          driver-class-name: org.mariadb.jdbc.Driver
          jdbc-url: jdbc:mariadb://127.0.0.1:11801/devwue?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
          username: root
          password: root
          pool-name: DBSlave-pool
          minimum-idle: 1
          maximum-pool-size: 5
          connection-timeout: 3000
          idle-timeout: 20000
          validation-timeout: 60000
          max-lifetime: 61000
          read-only: true
          data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true

logging:
  level:
    root: info
    org.springframework.web: info
    com.devwue: DEBUG
